apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-api.fullname" . }}
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.environment | quote }}
  FORCE_FAILURE: {{ .Values.config.forceFailure | quote }}
